import type { Customer, Ticket, Memory, Conversation, Resolution } from './types'
const companies = ['Arjun Technologies','Nova Systems','BluePeak Labs','Vertex Cloud','Cedarline Data','Orbit Ops','Northstar Digital','Pinecone Networks','Solstice Health','Quarry Systems']
export const customers: Customer[] = companies.map((company, i) => ({ id: `c-${i+1}`, name: ['Arjun Mehta','Maya Chen','Darius Cole','Priya Nair','Jon Bell','Elena Rossi','Samir Shah','Nora Kim','Tariq Wilson','Leah Morgan'][i], company, email: `support@${company.toLowerCase().replaceAll(' ','')}.example`, status: i === 4 ? 'At risk' : 'Active', since: ['Jan 2024','Mar 2024','Jun 2023','Sep 2024','Feb 2025','Nov 2023','Apr 2024','Aug 2024','May 2025','Dec 2023'][i], agent: ['Manikanta','Sofia Chen','Manikanta','Ava Patel'][i%4], openTickets: [4,2,1,3,0,2,1,4,2,1][i], memories: [38,19,26,31,12,22,17,29,14,24][i], lastInteraction: `${i+1}h ago`, environment: i === 0 ? ['AWS RDS','PostgreSQL 16','Node.js','Production'] : ['AWS','PostgreSQL','Production'], preferences: ['Prefers technical explanations','Prefers email follow-ups','Production incidents are high priority'].slice(0, i%3+1) }))
const ticketTitles = ['API timeout','Billing discrepancy','Deployment failure','Authentication issue','Database connection pool','Webhook delivery delays','Role permissions','Slow query performance','SAML configuration','Usage report mismatch','SDK initialization error','Production alert routing','Invoice export failure','Rate limit questions','Backup verification']
export const tickets: Ticket[] = Array.from({length: 24}, (_, i) => { const c = customers[i%customers.length]; return { id: `RD-${1048-i}`, customerId: c.id, customer: c.name, company: c.company, title: ticketTitles[i%ticketTitles.length], priority: (['High','Medium','High','Critical','Low'][i%5]) as Ticket['priority'], status: (['Open','Investigating','Resolved','Waiting','Escalated'][i%5]) as Ticket['status'], agent: c.agent, updated: `${i+1}h ago`, created: `Sep ${20-i}, 2026` } })
const memorySeed = [['Fact','Customer uses PostgreSQL 16.','Infrastructure'],['Experience','API timeout caused by connection-pool exhaustion.','Previous incident'],['Preference','Customer prefers detailed technical explanations.','Communication'],['Fact','Production runs on AWS RDS.','Infrastructure'],['Resolution','Increased pool size and added connection health checks.','Successful resolution'],['Relationship','Arjun Technologies has a production-first support plan.','Account context']]
export const memories: Memory[] = Array.from({length: 36}, (_, i) => { const c = customers[i%customers.length]; const seed = memorySeed[i%memorySeed.length]; return { id: `m-${i+1}`, type: seed[0] as Memory['type'], content: seed[1], context: seed[2], customerId: c.id, customer: c.company, remembered: `Sep ${20-(i%18)}, 2026`, lastRecalled: `${(i%6)+1}d ago`, source: `Conversation ${120+i}`, confidence: 0.88 + (i%10)/100 } })
export const resolutions: Resolution[] = [{id:'r-1',title:'Connection pool tuning',detail:'Raised max connections and added health checks.',customerId:'c-1',date:'Sep 15, 2026'},{id:'r-2',title:'Webhook retry policy',detail:'Added exponential backoff for transient failures.',customerId:'c-2',date:'Sep 11, 2026'}]
export const conversations: Conversation[] = [{ id:'conv-1', customerId:'c-1', ticketId:'RD-1048', messages:[{id:'1',author:'Arjun Mehta',role:'customer',content:'Our API is timing out again in production.',timestamp:'10:42 AM'},{id:'2',author:'Manikanta',role:'agent',content:'I’m looking into this now. I’ll compare it with the previous incident and check the connection pool metrics.',timestamp:'10:44 AM'},{id:'3',author:'Arjun Mehta',role:'customer',content:'The database is showing elevated connection counts.',timestamp:'10:46 AM'}]}]
export const analytics = { overview: [{label:'Total tickets',value:248,change:'+12.4%'},{label:'Resolution rate',value:86,change:'+4.2%'},{label:'Avg response time',value:18,change:'-8.1%'},{label:'Escalations',value:14,change:'-2.0%'}], recurring: [['API timeout',18],['Authentication',12],['Database connection',9],['Billing',7],['Deployment',6]] }
