import { customers, tickets, memories, conversations, analytics } from './mock-data'
import type { AuthState, Customer, Ticket, Memory, Conversation, AgentMessage, SearchResult, User } from './types'
export const authService = { async demoLogin(): Promise<AuthState> { return { demo: true, user: {id:'demo-1',name:'Manikanta',email:'manikanta@recalldesk.example',role:'Support Engineering'} } as AuthState }, async logout() { return null } }
export const customerService = { async list(): Promise<Customer[]> { return customers }, async get(id: string) { return customers.find(c => c.id === id) ?? customers[0] } }
export const ticketService = { async list(): Promise<Ticket[]> { return tickets }, async get(id: string) { return tickets.find(t => t.id === id) ?? tickets[0] } }
export const conversationService = { async getForCustomer(customerId: string): Promise<Conversation> { return conversations.find(c=>c.customerId===customerId) ?? conversations[0] } }
export const memoryService = { async getAll(): Promise<Memory[]> { return memories }, async getCustomerMemories(customerId: string) { return memories.filter(m=>m.customerId===customerId) }, async recall(customerId: string, query: string): Promise<Memory[]> { return memories.filter(m=>m.customerId===customerId || query.toLowerCase().includes('timeout')).slice(0,4) }, async retain() { return true } }
export const agentService = { async respond(customerId: string, message: string, withMemory: boolean): Promise<AgentMessage> { const content = withMemory ? 'Your current issue resembles the API timeout reported previously. The earlier incident involved connection-pool exhaustion on PostgreSQL 16 running in AWS RDS. I recommend checking pool saturation and health-check timeouts first.' : 'Can you tell me which database and infrastructure you are using, and whether this has happened before?' ; return {id: crypto.randomUUID(), role:'assistant',content,timestamp:'Just now',recalled:withMemory} } }
export const analyticsService = { async get() { return analytics } }
export function searchAll(query: string): SearchResult[] { const q=query.toLowerCase(); return [...customers.filter(c=>`${c.name} ${c.company}`.toLowerCase().includes(q)).map(c=>({kind:'Customer' as const,title:c.company,subtitle:c.name,href:`/customers/${c.id}`})), ...tickets.filter(t=>`${t.id} ${t.title}`.toLowerCase().includes(q)).map(t=>({kind:'Ticket' as const,title:`${t.id} · ${t.title}`,subtitle:t.company,href:`/tickets/${t.id}`})), ...memories.filter(m=>m.content.toLowerCase().includes(q)).map(m=>({kind:'Memory' as const,title:m.content,subtitle:m.customer,href:'/memory'}))].slice(0,8) }
